spring.threads.virtual.enabled: true
spring:
#  sql:
#    init:
#      mode: always
  datasource:
    url: jdbc:postgresql://pgdefault:5432/postgres
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: events

logging:
  level:
    root: info
    sql: debug
    web: debug
